# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x1qaQLSzsa55MWUztwF7Io_iSmOPoAW8
"""

!mkdir -p ai_project/tools

# Commented out IPython magic to ensure Python compatibility.
# # Create the __init__.py file in Colab
# %%writefile ai_project/tools/__init__.py
# from .web_search import web_search
# from .company_website import get_company_website
# from .dataset_search import search_datasets
# 
# __all__ = ['web_search', 'get_company_website', 'search_datasets']

