# -*- coding: utf-8 -*-
"""company_website.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rZcxzJok8vQGbSYvcXmFoPHBd-J5kcVH
"""

import requests
from bs4 import BeautifulSoup
from langchain.tools import tool
from pydantic import BaseModel, Field

class CompanyWebsiteInput(BaseModel):
    url: str = Field(..., description="URL of the company website")

@tool(args_schema=CompanyWebsiteInput)
def get_company_website(url: str) -> str:
    """Extract key information from a company website"""
    try:
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }
        response = requests.get(url, headers=headers, timeout=10)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, 'html.parser')

        sections = {
            'about': soup.find('section', {'id': 'about'}) or soup.find('div', class_='about'),
            'products': soup.find('section', {'id': 'products'}) or soup.find('div', class_='products'),
            'vision': soup.find('section', {'id': 'vision'}) or soup.find('div', class_='vision')
        }

        return "\n".join(
            f"{key.capitalize()}: {value.get_text(' ', strip=True)}"
            for key, value in sections.items()
            if value
        ) or "No key sections found"
    except Exception as e:
        return f"Error accessing website: {str(e)}"

