# -*- coding: utf-8 -*-
"""web_search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lPiXsr_rcGQJL7RUwz-Hf7bj1ajYL3d9
"""

!mkdir -p ai_project/tools

!pip install duckduckgo_search
from duckduckgo_search import DDGS
from langchain.tools import tool
from pydantic import BaseModel, Field

class WebSearchInput(BaseModel):
    query: str = Field(..., description="Search query to look up")

@tool(args_schema=WebSearchInput)
def web_search(query: str) -> str:
    """Search the web for current information about companies and industries"""
    try:
        with DDGS() as ddgs:
            results = [r for r in ddgs.text(query, max_results=5)]
            if not results:
                return "No results found"
            return "\n".join([
                f"{i+1}. {result['title']}\n"
                f"Link: {result['href']}\n"
                f"Description: {result['body']}\n"
                for i, result in enumerate(results)
            ])
    except Exception as e:
        return f"Search error: {str(e)}"